services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_2019
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tan0m#ho3s
    ports:
      - "1436:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sql_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge

volumes:
  sqlserver_data:
  redis_data:
